services:
  - type: web
    name: jurnal
    runtime: static
    buildCommand: bun install && bun run build
    staticPublishPath: dist/client
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
